# Generated by Django 4.0.3 on 2022-03-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('users', '0004_alter_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
