# Generated by Django 4.0.3 on 2022-03-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
    ]
