# Generated by Django 4.0.4 on 2022-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Saler', 'Saler'), ('Client', 'Clint')], default=('Client', 'Clint'), max_length=7),
        ),
    ]
