# Generated by Django 4.0.4 on 2022-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0009_busket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busket',
            name='product',
        ),
        migrations.AddField(
            model_name='busket',
            name='product',
            field=models.ManyToManyField(null=True, to='products.product'),
        ),
    ]
