# Generated by Django 4.0.4 on 2022-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_product_alter_productimage_title'),
        ('users', '0010_remove_busket_product_busket_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busket',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
