# Generated by Django 4.0.4 on 2022-04-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, editable=False, null=True, upload_to='images/product'),
        ),
    ]
