# Generated by Django 4.0.4 on 2022-05-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_image_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0),
        ),
        migrations.AlterField(
            model_name='brand',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='describtion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heigth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_sale',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='saled',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thicness',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weigth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
